modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="emeraldmod"
version="1.0"
displayName="Emerald Mod"
authors="Michael"
description='''Mod test nel chill :)'''

[[dependencies.emeraldmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.emeraldmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
